<OptionPopup>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: root.message
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: '44dp'
            Button:
                text: 'Yes'
                on_release: root.dispatch('on_answer', True)
            Button:
                text: 'No'
                on_release: root.dispatch('on_answer', False)