# Generated by Django 4.2.7 on 2023-11-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hashed',
        ),
    ]
